[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
test_build_src = true
test_filter = test_wifi_esp32
build_src_filter =
  +<WiFiESP32.cpp>
build_flags =
  -I test/mock
  -std=c++14

[env:native_mqtt]
platform = native
test_framework = unity
test_build_src = true
test_filter = test_mqtt_client_esp32
build_src_filter =
  +<MQTTClientESP32.cpp>
build_flags =
  -I test/mock
  -std=c++14

[env:native_settings]
platform = native
test_framework = unity
test_build_src = true
test_filter = test_settings_*
build_src_filter =
  +<settings/*.cpp>
build_flags =
  -I src
  -I test/settings_mock
  -D ARDUINOCOMMON_TEST_ESP32
  -std=c++14

[env:esp32_preferences_example]
platform = espressif32@6.10.0
framework = arduino
board = m5stack-atoms3
platform_packages = platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
build_src_filter = +<settings/*.cpp>
extra_scripts = pre:tools/build_preferences_example.py
build_flags =
  -D ARDUINOCOMMON_DISABLE_PROVISIONING
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
