#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


AUTO_HEADER = (
    "# Auto-generated from library.json and library.properties.template.\n"
    "# Do not edit this file by hand.\n"
)


def load_metadata(path: Path) -> dict[str, str]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"metadata file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"failed to parse JSON: {path}: {exc}") from exc

    name = raw.get("name")
    version = raw.get("version")
    if not isinstance(name, str) or not name.strip():
        raise SystemExit("library.json must contain a non-empty string field: name")
    if not isinstance(version, str) or not version.strip():
        raise SystemExit("library.json must contain a non-empty string field: version")
    return {"NAME": name, "VERSION": version}


def render(template: str, values: dict[str, str]) -> str:
    rendered = template
    for key, value in values.items():
        rendered = rendered.replace(f"{{{{{key}}}}}", value)
    if "{{" in rendered or "}}" in rendered:
        raise SystemExit("template contains unreplaced placeholders")
    return AUTO_HEADER + rendered


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Arduino library.properties from library.json metadata."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if library.properties is out of sync",
    )
    args = parser.parse_args()

    library_root = Path(__file__).resolve().parents[1]
    metadata_path = library_root / "library.json"
    template_path = library_root / "library.properties.template"
    output_path = library_root / "library.properties"

    values = load_metadata(metadata_path)
    try:
        template = template_path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise SystemExit(f"template file not found: {template_path}") from exc

    rendered = render(template, values)
    current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""

    if args.check:
        if current != rendered:
            print(f"{output_path} is out of sync", file=sys.stderr)
            return 1
        print(f"{output_path} is up to date")
        return 0

    output_path.write_text(rendered, encoding="utf-8", newline="\n")
    if current == rendered:
        print(f"{output_path} is already up to date")
    else:
        print(f"updated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
