/***********************************************************************/
/*                                                                     */
/*  FILE        :Log.hpp                                              */
/*  DATE        :Aug 13, 2020                                          */
/*  DESCRIPTION :ログ出力クラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#pragma once

#include <Arduino.h>
#include "Timer.h"

/***********************************************************************/
/*                           ログ出力クラス                            */
/***********************************************************************/
#define LOG_LEVEL_INIT (Log::ALL) // 出力ログレベルの初期値

class Log
{
public:
  // ログレベルの列挙型
  typedef enum elog
  {
    ALL,
    DEBUG,
    INFO,
    WARN,
    ERROR,
    NONE
  } logLevelEnum;
  Log();
  ~Log();
  logLevelEnum getLevel(void);
  void setLevel(logLevelEnum level);
  void log(logLevelEnum type, String msg);
  void info(String msg);
  void debug(String msg);
  void warn(String msg);
  void error(String msg);

private:
  logLevelEnum m_level;
};

extern Log logger;