/***********************************************************************/
/*                                                                     */
/*  FILE        :Log.cpp                                              */
/*  DATE        :Apl 21, 2021                                          */
/*  DESCRIPTION :ログ出力クラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#include <Arduino.h>

#include "Log.h"

/***********************************************************************/
/*                           ログ出力クラス                            */
/***********************************************************************/

Log::Log()
{
  serialBegin(LOG_SERIAL_BAUDRATE);
  m_level = LOG_LEVEL_INIT;
}

Log::~Log()
{
  serialEnd();
}

/**
 * @brief シリアル通信を開始する
 * 
 */
void Log::serialBegin(uint32_t baudrate)
{
#ifdef USE_M5ATOM_S3
  USBSerial.begin(baudrate);
#else
  Serial.begin(baudrate);
#endif
}

/**
 * @brief シリアル通信を終了する
 * 
 */
void Log::serialEnd(void)
{
#ifdef USE_M5ATOM_S3
  USBSerial.end();
#else
  Serial.end();
#endif
}

// 出力レベルを取得する
Log::logLevelEnum Log::getLevel(void)
{
  return m_level;
}

// 出力レベルを設定する
void Log::setLevel(logLevelEnum level)
{
  m_level = level;
}

void Log::log(logLevelEnum type, String msg)
{
  // ログ出力レベルのチェック
  if (type < m_level)
  {
    return; // 出力レベルが不足している場合は何もしない
  }

  String str = String(Timer::getGlobalTime());
  str.concat(",");
  if (type == DEBUG)
  {
    str.concat("DEBUG,");
  }
  else if (type == INFO)
  {
    str.concat("INFO,");
  }
  else if (type == WARN)
  {
    str.concat("WARN,");
  }
  else if (type == ERROR)
  {
    str.concat("ERROR,");
  }
  str.concat(msg);
#ifdef USE_M5ATOM_S3
  USBSerial.println(str);
#else
  Serial.println(str);
#endif
}

void Log::info(String msg)
{
  log(INFO, msg);
}

void Log::debug(String msg)
{
  log(DEBUG, msg);
}

void Log::warn(String msg)
{
  log(WARN, msg);
}

void Log::error(String msg)
{
  log(ERROR, msg);
}

/**
 * @brief ボーレートを変更する
 * 
 * @param baudrate 
 */
void Log::changeBaudrate(uint32_t baudrate)
{
  serialEnd();
  serialBegin(baudrate);
}

Log logger = Log();
