/***********************************************************************/
/*                                                                     */
/*  FILE        :Log.cpp                                              */
/*  DATE        :Apl 21, 2021                                          */
/*  DESCRIPTION :ログ出力クラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#include <Arduino.h>

#include "Log.h"

/***********************************************************************/
/*                           ログ出力クラス                            */
/***********************************************************************/

Log::Log()
{
#ifndef USE_M5ATOM_S3
  Serial.begin(115200);
#endif
  m_level = LOG_LEVEL_INIT;
}

Log::~Log()
{
#ifndef USE_M5ATOM_S3
  Serial.end();
#endif
}

// 出力レベルを取得する
Log::logLevelEnum Log::getLevel(void)
{
  return m_level;
}

// 出力レベルを設定する
void Log::setLevel(logLevelEnum level)
{
  m_level = level;
}

void Log::log(logLevelEnum type, String msg)
{
  // ログ出力レベルのチェック
  if (type < m_level)
  {
    return; // 出力レベルが不足している場合は何もしない
  }

  String str = String(Timer::getGlobalTime());
  str.concat(",");
  if (type == DEBUG)
  {
    str.concat("DEBUG,");
  }
  else if (type == INFO)
  {
    str.concat("INFO,");
  }
  else if (type == WARN)
  {
    str.concat("WARN,");
  }
  else if (type == ERROR)
  {
    str.concat("ERROR,");
  }
  str.concat(msg);
#ifndef USE_M5ATOM_S3
  USBSerial.println(str);
#else
  Serial.println(str);
#endif
}

void Log::info(String msg)
{
  log(INFO, msg);
}

void Log::debug(String msg)
{
  log(DEBUG, msg);
}

void Log::warn(String msg)
{
  log(WARN, msg);
}

void Log::error(String msg)
{
  log(ERROR, msg);
}

Log logger = Log();
