/***********************************************************************/
/*                                                                     */
/*  FILE        :Timer.hpp                                            */
/*  DATE        :Jun 28, 2020                                          */
/*  DESCRIPTION :タイマークラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/
#pragma once

#include <Arduino.h>

/***********************************************************************/
/*                           タイマー関数                              */
/***********************************************************************/

class Timer
{
public:
  // コンストラクタ
  Timer();
  // コンストラクタ(周期[ms])
  explicit Timer(uint16_t cycleTime);
  // 周期を設定する
  void setCycleTime(uint16_t time);
  uint16_t getCycleTime(void);
  // 周期が来たことを知らせ、フラグをクリアする（1:周期がきた、0:周期でない）
  uint8_t isCycleTime(void);
  // タイマーをクリアする
  void startTimer(void);
  // タイマー値[ms]を取得する
  uint32_t getTime(void);
  // タイマー値[ms]を取得する
  static uint32_t getGlobalTime(void) { return (millis()); }

private:
  uint32_t tempTimer; // 1msの割り込みでインクリメントされる変数
  uint32_t pastTime;  // 前回の時間/周期
  uint16_t cycleTime; // チェックする周期[ms]
};
